#### np basic functions

In [18]:
import numpy as np

a = np.array([[1,2,3,4], [1,2,3,4]], dtype='int64')

In [19]:
print(a)

[[1 2 3 4]
 [1 2 3 4]]


In [20]:
a.ndim

2

In [21]:
a.shape

(2, 4)

In [22]:
a.dtype

dtype('int64')

In [115]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### np.transpose

In [32]:
a = np.array([[1,2,3,4],[1,2,3,4]])

In [33]:
a.shape

(2, 4)

In [34]:
aT = np.transpose(a)

In [35]:
print(aT)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [36]:
aT.shape

(4, 2)

#### np.matmul

In [78]:
a = np.array([[1,2,3,4],[1,2,3,4]])

b = np.array([[1,2,3,4],[1,2,3,4]])

In [79]:
print(np.matmul(a,np.transpose(b)))

[[30 30]
 [30 30]]


In [84]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(np.matmul(a,b))

30


In [85]:
a.shape

(4,)

#### np.sum

In [45]:
np.sum(a)

20

In [46]:
np.sum(a,axis=0)

array([2, 4, 6, 8])

In [47]:
np.sum(a,axis=1)

array([10, 10])

In [48]:
np.sum(a,axis=-1)

array([10, 10])

In [51]:
a = np.array([[1,2,3,4],[1,2,3,4]])

b = np.array([[1,2,3,4],[1,2,3,4]])

#### Element wise operations

In [91]:
a = np.array([[1,2,3,4],[1,2,3,4]])

In [92]:
a+2

array([[3, 4, 5, 6],
       [3, 4, 5, 6]])

In [52]:
a*b

array([[ 1,  4,  9, 16],
       [ 1,  4,  9, 16]])

In [53]:
a+b

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [54]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
a/b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.transpose(a)@b # @ similar to np.matmul

array([[ 2,  4,  6,  8],
       [ 4,  8, 12, 16],
       [ 6, 12, 18, 24],
       [ 8, 16, 24, 32]])

#### Initializations

In [69]:
a = np.zeros((5,))
a

array([0., 0., 0., 0., 0.])

In [70]:
a = np.zeros((5,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [74]:
a = np.zeros((2,))
a

array([0., 0.])

In [72]:
a = np.ones((5,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### np.random

In [93]:
print(np.random.rand(2,3))

[[0.07080481 0.43084875 0.74308769]
 [0.46126429 0.68672449 0.25503995]]


In [99]:
print(np.random.randn(4,4))

[[ 0.97344155  0.92054894 -1.32608112  1.99535319]
 [ 1.57729911  0.83272636  0.56380967  1.07578498]
 [-0.03693027 -0.14761702  1.34018913 -0.94836756]
 [ 1.12891283  0.3129226  -0.91255498 -1.65748018]]


In [104]:
print(np.random.random((5,2)))

[[0.6532959  0.75730977]
 [0.9675281  0.5974228 ]
 [0.866826   0.40855587]
 [0.21441145 0.4633921 ]
 [0.29299684 0.67729636]]


In [114]:
print(np.random.randint(0,100,5))

[28 71  1 50  3]


In [109]:
l = ['hyderabad','bangalore', 'chennai', 'delhi','mumbai']
print(np.random.choice(l,10,p=[0.2,0.3,0.1,0.2,0.2]))

['delhi' 'mumbai' 'bangalore' 'hyderabad' 'mumbai' 'mumbai' 'bangalore'
 'mumbai' 'bangalore' 'chennai']


In [112]:
print(np.random.choice(5,10,p=[0.2,0.2,0.2,0.2,0.2]))

[0 3 0 1 1 1 2 1 1 0]


In [117]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
a = a.reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [120]:
np.random.shuffle(a)  # shuffle is inplace
print(a)

[[ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [127]:
np.random.permutation(a) # permutation returns the permuted ndarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.random.permutation(10)

array([6, 4, 1, 7, 0, 3, 8, 9, 5, 2])

In [125]:
np.random.shuffle([1,2,3,4]) # shuffle is inplace

In [126]:
np.random.permutation([1,2,3,4]) # permutation returns the permuted ndarray

array([3, 1, 4, 2])

In [128]:
#### random from different distributions